services:

  2048-server:
    restart: no
    image: nginx:1.29.3-alpine-slim
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html:ro

volumes:
  frontend:
